"""Code generation utilities for echem-viewer."""

from datetime import datetime

PLOT_TEMPLATE = '''#!/usr/bin/env python3
"""
Electrochemistry plot generated by echem-viewer
echem.helenengelhardt.ca

Generated: {timestamp}
"""

import polars as pl
import plotly.graph_objects as go
import plotly.express as px
from pathlib import Path

# Configuration
X_COLUMN = "{xcol}"
Y_COLUMN = "{ycol}"

# Plot settings
PLOT_TYPE = "{plot_type}"
COLOR_SCHEME = "{color_scheme}"
LINE_MODE = "{line_mode}"
MARKER_TYPE = "{marker_type}"
MARKER_SIZE = {marker_size}
TRACE_LINEWIDTH = {trace_linewidth}
AXIS_LINEWIDTH = {axis_linewidth}
X_SCALE = "{x_scale}"
Y_SCALE = "{y_scale}"
SHOW_GRID = {show_grid}
SHOW_LEGEND = {show_legend}
PLOT_HEIGHT = {plot_height}
PLOT_WIDTH = {plot_width}
TITLE = "{title}"
X_LABEL = "{x_label}"
Y_LABEL = "{y_label}"

# Files to plot (update paths as needed)
FILES = {files_list}

def load_data(file_path: str) -> pl.DataFrame:
    """Load data from parquet or csv file."""
    path = Path(file_path)
    if path.suffix == ".parquet":
        return pl.read_parquet(path)
    elif path.suffix == ".csv":
        return pl.read_csv(path)
    else:
        raise ValueError(f"Unsupported file format: {{path.suffix}}")

def create_plot():
    fig = go.Figure()

    # Get color palette
    palette = getattr(px.colors.sequential, COLOR_SCHEME, px.colors.sequential.Viridis)
    n = len(FILES)
    colors = [palette[int(i * (len(palette) - 1) / max(n - 1, 1))] for i in range(n)]

    for i, file_info in enumerate(FILES):
        file_path = file_info["path"]
        label = file_info.get("label", Path(file_path).stem)

        df = load_data(file_path)

        if X_COLUMN in df.columns and Y_COLUMN in df.columns:
            fig.add_trace(go.Scattergl(
                x=df[X_COLUMN].to_numpy(),
                y=df[Y_COLUMN].to_numpy(),
                mode=LINE_MODE,
                name=label,
                line=dict(color=colors[i], width=TRACE_LINEWIDTH),
                marker=dict(color=colors[i], size=MARKER_SIZE, symbol=MARKER_TYPE)
            ))

    # Layout
    axis_style = {{
        'linecolor': 'black',
        'linewidth': AXIS_LINEWIDTH,
        'ticks': 'inside',
        'tickwidth': AXIS_LINEWIDTH,
        'showline': True,
        'showgrid': SHOW_GRID,
        'gridcolor': 'lightgray',
        'gridwidth': 1,
        'griddash': 'dot',
        'mirror': True,
    }}

    layout = {{
        'plot_bgcolor': 'rgba(0, 0, 0, 0)',
        'font': {{'family': 'Arial Black', 'size': 16}},
        'title': {{'text': TITLE or f"EC Data ({{n}} files)"}},
        'xaxis': {{**axis_style, 'title': X_LABEL or X_COLUMN, 'type': X_SCALE}},
        'yaxis': {{**axis_style, 'title': Y_LABEL or Y_COLUMN, 'type': Y_SCALE}},
        'showlegend': SHOW_LEGEND,
        'height': PLOT_HEIGHT,
        'width': PLOT_WIDTH,
    }}

    fig.update_layout(**layout)
    return fig

if __name__ == "__main__":
    fig = create_plot()
    fig.show()
    # Optionally save as HTML: fig.write_html("plot.html")
'''


def generate_python_code(chart_values: dict, selected_files: list, file_metadata: dict | None) -> str:
    """Generate standalone Python code to recreate the plot.

    Args:
        chart_values: Dictionary of chart configuration values from chart_batch.value
        selected_files: List of selected filenames
        file_metadata: Dictionary mapping filenames to metadata dicts

    Returns:
        Python code as a string
    """
    v = chart_values
    xcol = v.get("x_col", "time/s")
    ycol = v.get("y_col", "<I>/mA")

    # Build files list for the code
    files_list = []
    for fname in selected_files:
        meta = file_metadata.get(fname, {}) if file_metadata else {}
        files_list.append({
            "path": fname.replace('.mpr', '.parquet'),
            "label": meta.get('label', fname.replace('.mpr', ''))
        })

    return PLOT_TEMPLATE.format(
        timestamp=datetime.now().isoformat(),
        xcol=xcol,
        ycol=ycol,
        plot_type=v.get("plot_type", "overlay"),
        color_scheme=v.get("color_scheme", "Viridis"),
        line_mode=v.get("line_mode", "lines"),
        marker_type=v.get("marker_type", "circle"),
        marker_size=v.get("marker_size", 6),
        trace_linewidth=v.get("trace_linewidth", 2),
        axis_linewidth=v.get("axis_linewidth", 4),
        x_scale=v.get("x_scale", "linear"),
        y_scale=v.get("y_scale", "linear"),
        show_grid=v.get("show_grid", True),
        show_legend=v.get("show_legend", True),
        plot_height=v.get("plot_height", 500),
        plot_width=v.get("plot_width", 800),
        title=v.get("plot_title", ""),
        x_label=v.get("x_label", ""),
        y_label=v.get("y_label", ""),
        files_list=repr(files_list)
    )
